packages:
  - '.'
overrides:
  nanoid: 3.3.18
  sharp: 0.35.5
  source-map-js: 1.2.2
allowBuilds:
  '@tailwindcss/oxide': set this to true or false
  esbuild: true
supportedArchitectures:
  os:
    - linux
  cpu:
    - x64
    - arm64
  libc:
    - glibc
