import Link from "next/link";
import { createSupabaseServerClient, isSupabaseConfigured } from "@/lib/supabase/server";
import { saveResident } from "./actions";

export const dynamic = "force-dynamic";

export default async function AdminResidenciasPage({ searchParams }: { searchParams: Promise<{ editar?: string; mensaje?: string }> }) {
  const { editar, mensaje } = await searchParams;
  if (!isSupabaseConfigured) return <Notice text="Configura Supabase para gestionar el directorio." />;
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return <Notice text="Inicia sesión desde el panel administrativo." />;
  const { data: roles } = await supabase.from("user_roles").select("role").eq("user_id", user.id);
  const permitted = roles?.some(({ role }) => role === "super_admin" || role === "events_admin");
  if (!permitted) return <Notice text="Tu cuenta no tiene permiso para gestionar residencias." />;
  const { data: residents } = await supabase.from("residents").select("*").order("residency_year", { ascending: false }).order("name");
  const { data: item } = editar ? await supabase.from("residents").select("*").eq("id", editar).maybeSingle() : { data: null };
  return <main className="min-h-screen bg-background px-6 py-10 text-foreground md:px-10"><div className="mx-auto max-w-5xl"><Link href="/admin" className="text-sm underline">← Panel</Link><div className="mt-5"><p className="text-xs font-bold tracking-widest text-[#0051A2] uppercase">Residencias</p><h1 className="text-3xl font-bold">{item ? "Editar residente" : "Directorio de residentes"}</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">El país, la nacionalidad y el año alimentan automáticamente el mapa público.</p></div>{mensaje === "residente-guardado" && <p className="mt-5 border border-[#99CC33] bg-[#99CC33]/15 p-4">Residente guardado correctamente.</p>}
    <form action={saveResident} className="mt-7 grid gap-4 border border-border bg-card p-6 md:grid-cols-2">{item && <input type="hidden" name="id" value={item.id} />}<label className="grid gap-2 font-semibold">Nombre del artista<input name="name" required defaultValue={item?.name ?? ""} className="border p-3 font-normal" /></label><label className="grid gap-2 font-semibold">Nacionalidad<input name="nationality" required placeholder="Colombiana" defaultValue={item?.nationality ?? ""} className="border p-3 font-normal" /></label><label className="grid gap-2 font-semibold">País<input name="country" required placeholder="Colombia" defaultValue={item?.country ?? ""} className="border p-3 font-normal" /></label><label className="grid gap-2 font-semibold">Año de residencia<input name="residency_year" type="number" min="2000" max="2100" required defaultValue={item?.residency_year ?? ""} className="border p-3 font-normal" /></label><label className="grid gap-2 font-semibold">Latitud del país<input name="country_lat" type="number" step="0.000001" min="-90" max="90" required placeholder="4.570868" defaultValue={item?.country_lat ?? ""} className="border p-3 font-normal" /></label><label className="grid gap-2 font-semibold">Longitud del país<input name="country_lng" type="number" step="0.000001" min="-180" max="180" required placeholder="-74.297333" defaultValue={item?.country_lng ?? ""} className="border p-3 font-normal" /></label><label className="grid gap-2 font-semibold md:col-span-2">Enlace al perfil o archivo (opcional)<input name="profile_url" type="url" placeholder="https://backup.platohedro.org/transpiksel/" defaultValue={item?.profile_url ?? ""} className="border p-3 font-normal" /></label><label className="grid gap-2 font-semibold md:col-span-2">Proyecto o nota (opcional)<textarea name="project" rows={3} defaultValue={item?.project ?? ""} className="border p-3 font-normal" /></label><div className="flex flex-wrap gap-3 md:col-span-2"><button name="publication" value="draft" className="border border-[#0051A2] px-5 py-3 font-bold text-[#0051A2]">Guardar borrador</button><button name="publication" value="published" className="bg-[#0051A2] px-5 py-3 font-bold text-white">Publicar en mapa</button>{item && <Link href="/admin/residencias" className="px-5 py-3 underline">Cancelar</Link>}</div></form>
    <section className="mt-12"><h2 className="text-2xl font-bold">Historial del directorio</h2>{residents?.length ? <div className="mt-5 divide-y border border-border">{residents.map((resident) => <div key={resident.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-bold">{resident.name}</p><p className="text-sm text-muted-foreground">{resident.nationality} · {resident.country} · {resident.residency_year}</p></div><div className="flex gap-4"><span className="text-sm">{resident.is_published ? "Publicado" : "Borrador"}</span><Link href={`/admin/residencias?editar=${resident.id}`} className="text-sm underline">Editar</Link></div></div>)}</div> : <p className="mt-5 border p-5 text-muted-foreground">Aún no hay residentes en el directorio.</p>}</section></div></main>;
}

function Notice({ text }: { text: string }) { return <main className="grid min-h-screen place-items-center p-6"><div className="max-w-md border p-8"><h1 className="text-2xl font-bold">Acceso a residencias</h1><p className="mt-3 text-muted-foreground">{text}</p><Link href="/admin" className="mt-5 inline-block underline">Volver al panel</Link></div></main>; }
