"use client";

import Link from "next/link";
import { useCart } from "@/app/components/CartProvider";
import { SiteHeader } from "@/app/components/SiteHeader";

export default function CartPage() {
  const { items, total, setQuantity, remove } = useCart();
  const startCheckout = async () => { const response = await fetch("/api/wompi/checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items: items.map(({ productId, quantity }) => ({ productId, quantity })) }) }); const data = await response.json() as { error?: string; checkoutUrl?: string; fields?: Record<string, string> }; if (!response.ok || !data.checkoutUrl || !data.fields) return alert(data.error || "No fue posible iniciar el pago."); const form = document.createElement("form"); form.method = "GET"; form.action = data.checkoutUrl; Object.entries(data.fields).forEach(([name, value]) => { const input = document.createElement("input"); input.type = "hidden"; input.name = name; input.value = value; form.append(input); }); document.body.append(form); form.submit(); };
  return <main className="min-h-screen bg-background"><SiteHeader /><section className="bg-[#003d7a] px-8 py-16 text-white"><h1 className="mx-auto max-w-6xl text-5xl font-bold">Carrito</h1></section><div className="mx-auto max-w-4xl p-8">{!items.length ? <div className="border p-8"><p>Tu carrito está vacío.</p><Link className="mt-5 inline-block underline" href="/tienda">Ver productos</Link></div> : <><div className="divide-y border">{items.map((item) => <div className="flex items-center gap-4 p-4" key={item.productId}>{item.imageUrl && <img src={item.imageUrl} alt={item.name} className="h-20 w-16 object-cover" />}<div className="flex-1"><h2 className="font-bold">{item.name}</h2><p>${item.priceCop.toLocaleString("es-CO")} COP</p></div><input aria-label={`Cantidad de ${item.name}`} className="w-16 border p-2" type="number" min="1" max="99" value={item.quantity} onChange={(event) => setQuantity(item.productId, Number(event.target.value))} /><button className="text-sm underline" onClick={() => remove(item.productId)}>Eliminar</button></div>)}</div><div className="mt-6 flex items-center justify-between border-t pt-6 text-xl font-bold"><span>Total</span><span>${total.toLocaleString("es-CO")} COP</span></div><p className="mt-6 text-sm text-muted-foreground">El stock y los precios se verifican nuevamente al iniciar el pago.</p><button className="mt-6 bg-[#99CC33] px-5 py-3 font-bold text-[#003d7a]" onClick={startCheckout}>Continuar al pago</button></>}</div></main>;
}
