-- Directorio historico suministrado por Platohedro (2014-2025).
-- Los registros importados no pertenecen a una cuenta administrativa concreta.
alter table public.residents alter column created_by drop not null;

with country_data(country, nationality, country_lat, country_lng) as (
  values
    ('Alemania', 'Colombiana/alemana', 52.520000::numeric, 13.405000::numeric),
    ('Argentina', 'Argentina', -34.603700, -58.381600),
    ('Brasil', 'Brasileña', -15.780100, -47.929200),
    ('Canadá', 'Canadiense', 45.421500, -75.697200),
    ('Cataluña', 'Catalana/mexicana', 41.387400, 2.168600),
    ('Chile', 'Chilena', -33.448900, -70.669300),
    ('Colombia', 'Colombiana', 4.570900, -74.297300),
    ('Costa Rica', 'Costarricense', 9.928100, -84.090700),
    ('Ecuador', 'Ecuatoriana', -0.180700, -78.467800),
    ('España', 'Española', 40.416800, -3.703800),
    ('Estados Unidos', 'Colombiana/estadounidense', 38.907200, -77.036900),
    ('Filipinas', 'Filipina', 14.599500, 120.984200),
    ('Francia', 'Francesa', 48.856600, 2.352200),
    ('Grecia', 'Griega', 37.983800, 23.727500),
    ('India', 'India/colombiana', 28.613900, 77.209000),
    ('Indonesia', 'Indonesia', -6.208800, 106.845600),
    ('Italia', 'Italiana', 41.902800, 12.496400),
    ('México', 'Mexicana', 19.432600, -99.133200),
    ('Nicaragua', 'Nicaragüense', 12.115000, -86.236200),
    ('Países Bajos', 'Neerlandesa/mexicana', 52.367600, 4.904100),
    ('Perú', 'Peruana', -12.046400, -77.042800),
    ('Reino Unido', 'Británica', 51.507400, -0.127800),
    ('Venezuela', 'Venezolana/brasileña', 10.480600, -66.903600)
),
historical_residents(name, country, residency_year, profile_url) as (
  values
    ('Radio Relajo', 'Colombia', 2014, 'https://platohedro.org/radio-relajo/'),
    ('Paula Pin', 'España', 2014, 'https://platohedro.org/paula-pin/'),
    ('Leandra Plaza', 'Colombia', 2015, 'https://platohedro.org/leandra-plaza/'),
    ('Hamilton Mestizo', 'Colombia', 2015, 'https://platohedro.org/hamilton-mestizo/'),
    ('Fabi Borges', 'Brasil', 2015, 'https://platohedro.org/fabiane-borges/'),
    ('Diego Peris', 'España', 2015, 'https://platohedro.org/diego-peris/'),
    ('Constanza Piña', 'Chile', 2015, 'https://platohedro.org/constanza-pina/'),
    ('Aniara Rodado', 'Colombia', 2015, 'https://platohedro.org/aniara-rodado/'),
    ('Angela Gabereau', 'Canadá', 2015, 'https://platohedro.org/angela-gabreau/'),
    ('Transpiksel', 'Chile', 2016, 'https://platohedro.org/transpiksel/'),
    ('Surofona', 'Argentina', 2016, 'https://platohedro.org/surofona/'),
    ('Siro Santos', 'España', 2016, 'https://platohedro.org/siro-santos/'),
    ('Marco Valdivia', 'Perú', 2016, 'https://platohedro.org/marco-valdivia/'),
    ('Lucía Egaña', 'Chile', 2016, 'https://platohedro.org/lucia-egana/'),
    ('Leslie García', 'México', 2016, 'https://platohedro.org/leslie-garcia/'),
    ('Laura Benech', 'Argentina', 2016, 'https://platohedro.org/laura-benech/'),
    ('Interspecifics', 'México', 2016, 'https://platohedro.org/interspecifics/'),
    ('Cristian Oyarzun', 'Chile', 2016, 'https://platohedro.org/cristian-oyarzun/'),
    ('Claudia Godoy', 'Chile', 2016, 'https://platohedro.org/claudia-godoy/'),
    ('Catherine Young', 'Filipinas', 2016, 'https://platohedro.org/catherine-young/'),
    ('Alejandro Hurtado', 'Colombia', 2016, 'https://platohedro.org/alejandro-hurtado/'),
    ('Yessica Diaz', 'México', 2017, 'https://platohedro.org/yessica-diaz/'),
    ('Sharath Chandra + Catalina Alzate', 'India', 2017, 'https://platohedro.org/sharath-chandra-catalina-alzate/'),
    ('Olivia Jack', 'Estados Unidos', 2017, 'https://platohedro.org/olivia-jack/'),
    ('Nadia Granados', 'Colombia', 2017, 'https://platohedro.org/nadia-granados/'),
    ('Lucca Carruba', 'Colombia', 2017, 'https://platohedro.org/lucca-carruba/'),
    ('Jorge Crowe', 'Argentina', 2017, 'https://platohedro.org/jorge-crowe/'),
    ('Ingrid Cuestas', 'Colombia', 2017, 'https://platohedro.org/ingrid-cuestas/'),
    ('Fred Paulino', 'Brasil', 2017, 'https://platohedro.org/fred-paulino/'),
    ('Fernando Godoy + Paola Rus', 'Chile', 2017, 'https://platohedro.org/fernando-godoy-paola-rus/'),
    ('Corina Salas + Dé', 'Venezuela', 2017, 'https://platohedro.org/corina-salas-de/'),
    ('RGGTRN', 'México', 2017, 'https://platohedro.org/colectivo-rggtrn/'),
    ('Carme Gomila + Pablo Lucero', 'España', 2017, 'https://platohedro.org/carme-gomila-pablo-lucero/'),
    ('Carles Soler', 'España', 2017, 'https://platohedro.org/carles-soler/'),
    ('Augustin Soulard', 'Francia', 2017, 'https://platohedro.org/augustin-soulard/'),
    ('Álvaro Valls + Clara Megías', 'España', 2017, 'https://platohedro.org/alvaro-valls-clara-mejias/'),
    ('Aldo Ramos', 'Países Bajos', 2017, 'https://platohedro.org/aldo-ramos/'),
    ('Aniara Rodado', 'Colombia', 2017, 'https://platohedro.org/aniara-rodado-2/'),
    ('Yela Quim', 'Colombia', 2018, 'https://platohedro.org/yela-quim/'),
    ('Santiago Parada', 'Colombia', 2018, 'https://platohedro.org/santiago-parada/'),
    ('Vânia Medeiros', 'Brasil', 2018, 'https://platohedro.org/vania-medeiros/'),
    ('Valeria Maggliochetti + Álvaro Pansa', 'Argentina', 2018, 'https://platohedro.org/valeria-maggliochetti-alvaro-pansa/'),
    ('Roxanne Minten', 'Países Bajos', 2018, 'https://platohedro.org/roxanne-minten/'),
    ('Patrick Dionne + Miki Gingras', 'Canadá', 2018, 'https://platohedro.org/patrick-dionne-miki-gingra/'),
    ('Lifepatch', 'Indonesia', 2018, 'https://platohedro.org/lifepatch/'),
    ('José Manuel González Martinez', 'España', 2018, 'https://platohedro.org/jose-manuel-gonzalez-martinez/'),
    ('Isabelle Arvers', 'Francia', 2018, 'https://platohedro.org/isabelle-arvers/'),
    ('Eric Barbosa + Clara Bastos', 'Brasil', 2018, 'https://platohedro.org/eric-barbosa-clara-bastos/'),
    ('Elina Rodriguez', 'Argentina', 2018, 'https://platohedro.org/elina-rodriguez/'),
    ('Ana Peñas', 'España', 2018, 'https://platohedro.org/ana-penas/'),
    ('Alexandra Cárdenas', 'Alemania', 2018, 'https://platohedro.org/alexandra-cardenas/'),
    ('Roberto Guillén', 'Nicaragua', 2019, 'https://platohedro.org/roberto-guillen/'),
    ('Randall Sáenz', 'Costa Rica', 2019, 'https://platohedro.org/randall-saenz/'),
    ('Pedro Soler', 'Ecuador', 2019, 'https://platohedro.org/pedro-soler/'),
    ('José Venditti', 'España', 2019, 'https://platohedro.org/jose-venditti/'),
    ('Emilio Sánchez Galán', 'México', 2019, 'https://platohedro.org/emilio-sanchez-galan/'),
    ('Dora Bartilotti', 'México', 2019, 'https://platohedro.org/dora-bartilotti/'),
    ('Colectivo 22bits', 'Chile', 2019, 'https://platohedro.org/colectivo-22-bits/'),
    ('Carles Tardío Pi', 'Cataluña', 2019, 'https://platohedro.org/andrea-ganuza-2/'),
    ('Andrea Ganuza', 'España', 2019, 'https://platohedro.org/andrea-ganuza/'),
    ('Santiago Bedoya Jaramillo', 'Colombia', 2020, 'https://platohedro.org/andrea-ganuza/'),
    ('Luis Navarro', 'México', 2020, 'https://platohedro.org/luis-navarro/'),
    ('Neilton Dos Reis', 'Brasil', 2020, 'https://platohedro.org/neilton-dos-reis/'),
    ('Marcela Vargas + Yenny León', 'Colombia', 2020, 'https://platohedro.org/marcela-vargas-y-yenny-leon/'),
    ('Ce Pams', 'Chile', 2020, 'https://platohedro.org/ce-pams/'),
    ('Analú Laferal', 'Colombia', 2020, 'https://platohedro.org/analu-laferal/'),
    ('Milena Contreras', 'Colombia', 2021, 'https://platohedro.org/milena-contreras/'),
    ('Eliana Morales Zuluaga', 'Colombia', 2022, 'https://platohedro.org/eliana-morales-zuluaga/'),
    ('Estefanía Henao', 'Colombia', 2022, 'https://platohedro.org/estefania-henao-2/'),
    ('Leifer Hoyos Madrid', 'Colombia', 2023, 'https://platohedro.org/leifer-hoyos-madrid/'),
    ('Yasmine Ostendorf-Rodríguez', 'Países Bajos', 2023, 'https://platohedro.org/yazmine-ostendorf-rodriguez/'),
    ('Penny Travlov', 'Grecia', 2023, 'https://platohedro.org/penny-travlov/'),
    ('Sara Gomez Whooley', 'Estados Unidos', 2024, 'https://platohedro.org/sara-gomez-whooley/'),
    ('Sandra Ramirez', 'Colombia', 2024, 'https://platohedro.org/sandra-ramirez/'),
    ('Laura Sofia Montoya', 'Colombia', 2024, 'https://platohedro.org/laura-sofia-montoya/'),
    ('Maria Carolina Ardila', 'Colombia', 2024, 'https://platohedro.org/maria-carolina-ardila/'),
    ('Laura Velandia', 'Colombia', 2025, 'https://platohedro.org/laura-velandia-mandala/'),
    ('Aliens Institute', 'Colombia', 2025, 'https://platohedro.org/aliens-institute/'),
    ('Vivien Ayroles', 'Francia', 2025, 'https://platohedro.org/vivien-ayroles/'),
    ('Clémence Vazard', 'Francia', 2025, 'https://platohedro.org/clemence-vazard/'),
    ('Julix Mercury', 'Colombia', 2025, 'https://platohedro.org/julix-mercury/'),
    ('Sophia Cull', 'Reino Unido', 2025, 'https://platohedro.org/sophia-cull/'),
    ('La Mirla', 'Colombia', 2025, 'https://platohedro.org/sara-gomez-whooley-2/')
)
insert into public.residents (
  name, nationality, country, country_lat, country_lng, residency_year,
  project, profile_url, is_published, created_by
)
select
  historical.name,
  countries.nationality,
  historical.country,
  countries.country_lat,
  countries.country_lng,
  historical.residency_year,
  'Importado del directorio histórico suministrado por Platohedro.',
  historical.profile_url,
  true,
  null
from historical_residents historical
join country_data countries using (country)
where not exists (
  select 1
  from public.residents existing
  where lower(trim(existing.name)) = lower(trim(historical.name))
    and existing.residency_year = historical.residency_year
);

notify pgrst, 'reload schema';
